name: socialme
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  image_picker: ^1.0.4
  beamer: ^1.5.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  hooks_riverpod: ^2.4.1
  flutter_hooks: ^0.20.1
  mockito: ^5.4.2
  injectable: ^2.1.2
  get_it: ^7.6.0
  getwidget: ^4.0.0
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.5.0
  intl: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
